name = "ccc-keitsz-english"
compatibility_date = "2026-05-14"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "english-etools"
database_id = "ebc786ea-f275-4627-a729-f1bfb6f593ae"

[vars]
ADMIN_PASSWORD = "keitsz2026"
